version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}

services:

  alpine-sample:
    image: alpine-sample:latest
    container_name: alpine-sample
    restart: always
    build:
      context: .
    environment:
      <<: *shared_environment
      SSH_INTERNAL_PORT: ${SSH_INTERNAL_PORT}
    ports:
      - ${SSH_EXTERNAL_PORT}:${SSH_INTERNAL_PORT}
